version: "3.6"
services:
  base:
    container_name: surittec-backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/src"
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
